// Auto-sync `public/demo/` → `src/lib/demos.generated.ts`.
//
// Run via `pnpm run sync:demos`, or implicitly chained from `dev` / `build`.
// Drop a file into `public/demo/`, restart, and the playground's "Load Demo"
// button picks it up — no edits to `demos.ts`.

import { readdirSync, statSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, extname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const PLAYGROUND_DIR = resolve(__dirname, "..");
const DEMO_DIR = join(PLAYGROUND_DIR, "public", "demo");
const OUTPUT_FILE = join(PLAYGROUND_DIR, "src", "lib", "demos.generated.ts");

// Extension → MIME map. Extend here when you drop in a new format.
const MIME_MAP = {
  ".pdf": "application/pdf",
  ".pptx":
    "application/vnd.openxmlformats-officedocument.presentationml.presentation",
  ".ppt": "application/vnd.ms-powerpoint",
  ".xlsx":
    "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
  ".xls": "application/vnd.ms-excel",
  ".docx":
    "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
  ".doc": "application/msword",
  ".epub": "application/epub+zip",
  ".html": "text/html",
  ".htm": "text/html",
  ".png": "image/png",
  ".jpg": "image/jpeg",
  ".jpeg": "image/jpeg",
  ".gif": "image/gif",
  ".webp": "image/webp",
  ".svg": "image/svg+xml",
  ".bmp": "image/bmp",
  ".ico": "image/x-icon",
  ".mp4": "video/mp4",
  ".webm": "video/webm",
  ".mov": "video/quicktime",
  ".mp3": "audio/mpeg",
  ".wav": "audio/wav",
  ".ogg": "audio/ogg",
  ".m4a": "audio/mp4",
  ".md": "text/markdown",
  ".mdx": "text/markdown",
  ".json": "application/json",
  ".csv": "text/csv",
  ".txt": "text/plain",
  ".log": "text/plain",
  ".rtf": "application/rtf",
  ".zip": "application/zip",
  ".js": "text/javascript",
  ".ts": "text/typescript",
  ".tsx": "text/typescript",
  ".jsx": "text/javascript",
  ".py": "text/x-python",
  ".rs": "text/x-rust",
  ".go": "text/x-go",
  ".java": "text/x-java",
  ".css": "text/css",
  ".yml": "text/yaml",
  ".yaml": "text/yaml",
  ".toml": "application/toml",
  ".xml": "application/xml",
};

function inferMime(filename) {
  return MIME_MAP[extname(filename).toLowerCase()] ?? "application/octet-stream";
}

function listDemoFiles() {
  let entries;
  try {
    entries = readdirSync(DEMO_DIR);
  } catch (err) {
    if (err.code === "ENOENT") {
      console.warn(`[sync-demos] ${DEMO_DIR} does not exist — emitting empty list`);
      return [];
    }
    throw err;
  }
  return entries
    .filter((name) => !name.startsWith(".")) // skip .gitkeep, .DS_Store, etc.
    .map((name) => {
      const full = join(DEMO_DIR, name);
      const stat = statSync(full);
      if (!stat.isFile()) return null;
      return {
        name,
        path: `/demo/${name}`,
        type: inferMime(name),
        size: stat.size,
      };
    })
    .filter(Boolean)
    .sort((a, b) => a.name.localeCompare(b.name, "zh-CN"));
}

function render(entries) {
  const header = `// AUTO-GENERATED by apps/playground/scripts/sync-demos.mjs
// Do not edit — drop files into apps/playground/public/demo/ and re-run
// \`pnpm run sync:demos\` (or just \`pnpm run dev\` / \`pnpm run build\`).

export interface DemoFileEntry {
  /** Original filename, e.g. "report.pdf" */
  name: string;
  /** URL path under public, e.g. "/demo/report.pdf" — pass to resolveAssetPath() */
  path: string;
  /** MIME type inferred from file extension */
  type: string;
  /** File size in bytes (informational) */
  size: number;
}

export const DEMO_FILE_ENTRIES: DemoFileEntry[] = ${JSON.stringify(entries, null, 2)};
`;
  return header;
}

function main() {
  const entries = listDemoFiles();
  mkdirSync(dirname(OUTPUT_FILE), { recursive: true });
  writeFileSync(OUTPUT_FILE, render(entries), "utf8");
  console.log(
    `[sync-demos] wrote ${entries.length} entries → ${OUTPUT_FILE.replace(PLAYGROUND_DIR, "apps/playground")}`
  );
}

main();
